apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /app/
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /app/
        pathType: Prefix
        backend:
          service:
            name: devops-backend
            port:
              number: 8081