services:
  devops-db:
    image: mariadb
    container_name: devops-db
    ports:
      - 3390:3306
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=devops
      - MYSQL_PASSWORD=devops
      - MYSQL_USER=devops
      - MYSQL_DATABASE=devops-db

  devops-backend:
    image: smouchlianitis/devops-backend:latest
    container_name: devops-backend
    ports:
      - 8081:8081
    depends_on:
      - devops-db